GET http://localhost:8000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySWQiOjEsIm5hbWUiOiJBbGZhUml6YSIsImVtYWlsIjoibWFsZmFyaXphNDVAZ21haWwuY29tIiwiaWF0IjoxNjUyMDExNjU2LCJleHAiOjE2NTIwMTE2NzF9.WCiJ0nf10LBgeERiEfwy-8u_M0vnd6dxWcMOghhpDEQ
###
POST http://localhost:8000/register
Content-Type: application/json

{
    "name": "AlfaRiza",
    "email": "malfariza45@gmail.com",
    "password": "12345678",
    "confirm_password": "12345678"
}

###
POST http://localhost:8000/login
Content-Type: application/json

{
    "email": "malfariza45@gmail.com",
    "password": "12345678"
}

###
GET http://localhost:8000/token


###
DELETE  http://localhost:8000/logout